//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace t6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Display(Name = "用户ID")]
        public int userid { get; set; }
        [Display(Name ="用户名")]
        public string username { get; set; }
        [Display(Name = "密码")]
        public string pwd { get; set; }
        [Display(Name = "邮箱")]
        public string email { get; set; }
        [Display(Name = "昵称")]
        public string nick { get; set; }
        [Display(Name = "QQ")]
        public string QQ { get; set; }
        [Display(Name = "电话")]
        public string phone { get; set; }
        [Display(Name = "安全问题")]
        public string question { get; set; }
        [Display(Name = "安全密码")]
        public string secPwd { get; set; }
    }
}
